# Generated by Django 3.1.2 on 2020-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20201002_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(related_name='employees', to='companies.Company'),
        ),
    ]
